### PR TITLE
Fix issue with type mismatch in helper template

### PR DESCRIPTION
**Pull request by krmichelos**
The or function expects Boolean parameters and license is a string.  This takes care of converting it based on contents.

Signed-off-by: Kyle Michel <kyle.michel@finvi.com>

### CODE REVIEW

**Comment by krmichelos** [comment]
@tamalsaha Ran into this when trying the new chart for the enterprise image with a license.  Had to revert to chart 0.14.1 for now.

**Comment by tamalsaha** [comment]
Thanks @krmichelos !

**Comment by krmichelos** [comment]
@tamalsaha, my ide fixed the chart version to be a valid semver, but that looks like it has broken some verify checks.  Do you want me to make another PR to put the v back or to work through not having it in the chart version?

**Comment by tamalsaha** [comment]
No worries. I have fixed it.

**Comment by tamalsaha** [comment]
chart version v0.14.3 is published

**Pull request merged**
